### ISSUE TITLE
Problem with "WITH common_table_expression"

### ISSUE THREAD

**Issue by charlesd** [cretz/node-tds#18]
I keep getting error message when tried to execute statements with "WITH common_table_expression".  http://msdn.microsoft.com/en-us/library/ms175972(v=sql.90).aspx

"WITH common_table_expression" is an extremely useful new feature added since SQL Server 2005.  I really hope this issue can be fixed soon.

**Comment by rickbergfalk** [comment]
@charlesd,

What exactly is the error you are receiving? I've been able to pass a working CTE statement through tds... My guess is the SQL is potentially not fully formed the way it should be.

Feel free to post your SQL and I'll see if I can help with any of it.

**Comment by charlesd** [comment]
I found that it's actually the ORDER BY statement caused the problem.  The statement was tested ok when running in MSSMS.  Then I looked into tds source code.  Switched to debug mode.  It tells me that the order token cannot be recognized.  I added a short script to handle the order token immediately fixed the problem.  No problem for tds to handle CTE as long as no ORDER BY in the statement.

**Comment by cretz** [comment]
Ok, I'll work on a test case for this. It is very likely I haven't properly implemented [ORDER](http://msdn.microsoft.com/en-us/library/dd303317%28v=prot.13%29.aspx) properly.

**Comment by cretz** [comment]
Before I write this test case, can you verify this has a problem on master (not the version in npm)? I believe I fixed it as part of issue #4.

**Comment by charlesd** [comment]
Oh.  I was using the version from npm.  I will test it with the latest version.

**Comment by charlesd** [comment]
The new version works fine.  Thanks for your help.
