### ISSUE TITLE
createStatement in row event handling

### ISSUE THREAD

**Issue by charlesd** [cretz/node-tds#21]
I'm trying to run a second query in response to the first one.  But I keep getting error "Statement currently running" when trying to create the 2nd statement.  Here is my code:

```
var conn = new tds.Connection({
    host: 'localhost',
    port: 1433,
    database: 'DBTEST',
    userName: 'user',
    password: 'pass'
});

var stmt = conn.createStatement("select 1");
stmt.on('row', function(row){
    var stmt2 = conn.createStatement("select 2");
    stmt2.on('row', function(row){
        console.log('query 2 row');
    });
    stmt2.on('done', function(e){
        console.log('query 2 done');
        console.log('query 1 row');
    });
    stmt2.execute();
});
stmt.on('done', function(e){
    console.log('query 1 done');
});
stmt.execute();
```

I'm not very experienced in event driven coding.  Am I doing something wrong here? 
Thank a lot for your help and the wonderful project.

**Comment by cretz** [comment]
Currently node-tds only supports one active statement per connection. MARS (Mulitple Active Result Set) support is planned, but the implementation is rather difficult. I have created issue #22 so you can follow it if I ever add MARS support. In the meantime, use one connection per statement and use something like node-pool to manage your connections.
