### ISSUE TITLE
parameters in where clause

### ISSUE THREAD

**Issue by noregrets** [cretz/node-tds#23]
More of a question than an issue:  Is it possible to use parameters in the where clause of a statement?  I tried it a couple different ways with no success, but thought I should ask before spending too much time trying to figure something out that isn't a feature.

Thanks!

**Comment by cretz** [comment]
Yes you can, but only as values. You can't do string substitution or anything. All parameterization really does is defer to [sp_executesql](http://msdn.microsoft.com/en-us/library/ms188001.aspx). So something like WHERE ColumnName = @ColumnValue works just fine.

Need more info? Got a sample query that fails that should work?

**Comment by noregrets** [comment]
Embarrassingly enough, the problem was that I didn't define a large enough size for my parameter.  Thanks for the great module!
